name: CI

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
    - name: Install dependencies
      run: |
        cd my-app &
        npm run build
    - name: Run component tests
      run: |
        cd my-app
        npm run test
    - name: Start the app
      run: |
        cd my-app
        npm start & 
        npx wait-on --timeout 60000
